[settings]
class = "Exports"
doc_group = "001-Route"
doc_descr = "internal-use only data model detailing a single index chunk file"
doc_route = "100-exports"
attributes = ""
produced_by = "exports"
disable_go = false

[[facets]]
name = "Assets"
store = "Assets"
viewType = ""

[[facets]]
name = "Balances"
store = "Balances"
viewType = ""

[[facets]]
name = "Statements"
store = "Statements"
viewType = ""
