// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAddress(arg1) {
  return window['go']['project']['Project']['AddAddress'](arg1);
}

export function GetActiveAddress() {
  return window['go']['project']['Project']['GetActiveAddress']();
}

export function GetActiveChain() {
  return window['go']['project']['Project']['GetActiveChain']();
}

export function GetActivePeriod() {
  return window['go']['project']['Project']['GetActivePeriod']();
}

export function GetAddresses() {
  return window['go']['project']['Project']['GetAddresses']();
}

export function GetChains() {
  return window['go']['project']['Project']['GetChains']();
}

export function GetLastFacet(arg1) {
  return window['go']['project']['Project']['GetLastFacet'](arg1);
}

export function GetLastView() {
  return window['go']['project']['Project']['GetLastView']();
}

export function GetName() {
  return window['go']['project']['Project']['GetName']();
}

export function GetPath() {
  return window['go']['project']['Project']['GetPath']();
}

export function RemoveAddress(arg1) {
  return window['go']['project']['Project']['RemoveAddress'](arg1);
}

export function Save() {
  return window['go']['project']['Project']['Save']();
}

export function SaveAs(arg1) {
  return window['go']['project']['Project']['SaveAs'](arg1);
}

export function SetActiveAddress(arg1) {
  return window['go']['project']['Project']['SetActiveAddress'](arg1);
}

export function SetActiveChain(arg1) {
  return window['go']['project']['Project']['SetActiveChain'](arg1);
}

export function SetActivePeriod(arg1) {
  return window['go']['project']['Project']['SetActivePeriod'](arg1);
}

export function SetLastFacet(arg1, arg2) {
  return window['go']['project']['Project']['SetLastFacet'](arg1, arg2);
}

export function SetLastView(arg1) {
  return window['go']['project']['Project']['SetLastView'](arg1);
}

export function SetName(arg1) {
  return window['go']['project']['Project']['SetName'](arg1);
}

export function SetViewAndFacet(arg1, arg2) {
  return window['go']['project']['Project']['SetViewAndFacet'](arg1, arg2);
}
